version: '2.1'

services:
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host
  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
  dnscrypt-proxy:
    build: ./balena-pihole/dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./balena-sound/bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  airplay:
    build: ./balena-sound/airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
  spotify:
    build: ./balena-sound/spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify

volumes:
  pihole_config: {}
  dnsmasq_config: {}
  dnscrypt_config: {}
  spotifycache: {}
  bluetoothcache: {}